apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - env:
        envFrom:
          - configMapRef:
              name: access-env
        name: django
        command: ["/gunicorn.sh"]
        image: blowhorn_django
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app
          name: django-volume
      volumes:
      - name: django-volume
        hostPath:
         # directory location on host
          path: /home/ubuntu/blowhorn
         # this field is optional
          type: Directory
      restartPolicy: "Always"
