apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - env:
        envFrom:
          - configMapRef:
              name: access-env
        name: worker
        command: ["/run-celeryworker.sh"]
        image: blowhorn_worker
        imagePullPolicy: Never
      restartPolicy: "Always"
