apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: "80"
    port: 8080
    targetPort: 80
  - name: "443"
    port: 443
  selector:
    app: nginx

